import kansas from "../../logos/kansas_logo.png";
import texas from "../../logos/Texas_Longhorns.png";
import texasAandM from "../../logos/a&m.png";
import bama from "../../logos/bama.png";
import ducks from "../../logos/ducks.png";
import huskies from "../../logos/huskies.png";
import michigan from "../../logos/michigan.png";
import fsu from "../../logos/michigan.png";

export const mockOpponents = [
  {
    id: 1,
    logo: kansas,
    date: "01-14-2024",
    time: "6:00 PM",
    theme: "Pink Game",
    sponsor: "OU Health",
    associatedSponsor: null,
    sspTickets: null,
    anthem: "Choir",
    emcee: "Tommy",
    pa: "Justin Wollard",
    colorGuard: null,
    halftime: "Bethel Lady Pirates Basketball Scrimmage",
    recognitions: "Patriot of the Game",
    kidsZone: null,
    concourse: null,
    spirit: null,
    giveaway: null,
    ticketPromo: null,
    consessions: "$2 Consessions",
    otherActivities: null,
  },
  {
    id: 2,
    logo: texas,
    date: "01-14-2024",
    time: "6:00 PM",
    theme: "Pink Game",
    sponsor: "OU Health",
    associatedSponsor: null,
    sspTickets: null,
    anthem: "Choir",
    emcee: "Tommy",
    pa: "Justin Wollard",
    colorGuard: null,
    halftime: "Bethel Lady Pirates Basketball Scrimmage",
    recognitions: "Patriot of the Game",
    kidsZone: null,
    concourse: null,
    spirit: null,
    giveaway: null,
    ticketPromo: null,
    consessions: "$2 Consessions",
    otherActivities: null,
  },
  {
    id: 3,
    logo: bama,
    date: "01-14-2024",
    time: "6:00 PM",
    theme: "Pink Game",
    sponsor: "OU Health",
    associatedSponsor: null,
    sspTickets: null,
    anthem: "Choir",
    emcee: "Tommy",
    pa: "Justin Wollard",
    colorGuard: null,
    halftime: "Bethel Lady Pirates Basketball Scrimmage",
    recognitions: "Patriot of the Game",
    kidsZone: null,
    concourse: null,
    spirit: null,
    giveaway: null,
    ticketPromo: null,
    consessions: "$2 Consessions",
    otherActivities: null,
  },
  {
    id: 4,
    logo: ducks,
    date: "01-14-2024",
    time: "6:00 PM",
    theme: "Pink Game",
    sponsor: "OU Health",
    associatedSponsor: null,
    sspTickets: null,
    anthem: "Choir",
    emcee: "Tommy",
    pa: "Justin Wollard",
    colorGuard: null,
    halftime: "Bethel Lady Pirates Basketball Scrimmage",
    recognitions: "Patriot of the Game",
    kidsZone: null,
    concourse: null,
    spirit: null,
    giveaway: null,
    ticketPromo: null,
    consessions: "$2 Consessions",
    otherActivities: null,
  },
  {
    id: 5,
    logo: huskies,
    date: "01-14-2024",
    time: "6:00 PM",
    theme: "Pink Game",
    sponsor: "OU Health",
    associatedSponsor: null,
    sspTickets: null,
    anthem: "Choir",
    emcee: "Tommy",
    pa: "Justin Wollard",
    colorGuard: null,
    halftime: "Bethel Lady Pirates Basketball Scrimmage",
    recognitions: "Patriot of the Game",
    kidsZone: null,
    concourse: null,
    spirit: null,
    giveaway: null,
    ticketPromo: null,
    consessions: "$2 Consessions",
    otherActivities: null,
  },
  {
    id: 6,
    logo: fsu,
    date: "01-14-2024",
    time: "6:00 PM",
    theme: "Pink Game",
    sponsor: "OU Health",
    associatedSponsor: null,
    sspTickets: null,
    anthem: "Choir",
    emcee: "Tommy",
    pa: "Justin Wollard",
    colorGuard: null,
    halftime: "Bethel Lady Pirates Basketball Scrimmage",
    recognitions: "Patriot of the Game",
    kidsZone: null,
    concourse: null,
    spirit: null,
    giveaway: null,
    ticketPromo: null,
    consessions: "$2 Consessions",
    otherActivities: null,
  },
  {
    id: 7,
    logo: texasAandM,
    date: "01-14-2024",
    time: "6:00 PM",
    theme: "Pink Game",
    sponsor: "OU Health",
    associatedSponsor: null,
    sspTickets: null,
    anthem: "Choir",
    emcee: "Tommy",
    pa: "Justin Wollard",
    colorGuard: null,
    halftime: "Bethel Lady Pirates Basketball Scrimmage",
    recognitions: "Patriot of the Game",
    kidsZone: null,
    concourse: null,
    spirit: null,
    giveaway: null,
    ticketPromo: null,
    consessions: "$2 Consessions",
    otherActivities: null,
  },
  {
    id: 8,
    logo: michigan,
    date: "01-14-2024",
    time: "6:00 PM",
    theme: "Pink Game",
    sponsor: "OU Health",
    associatedSponsor: null,
    sspTickets: null,
    anthem: "Choir",
    emcee: "Tommy",
    pa: "Justin Wollard",
    colorGuard: null,
    halftime: "Bethel Lady Pirates Basketball Scrimmage",
    recognitions: "Patriot of the Game",
    kidsZone: null,
    concourse: null,
    spirit: null,
    giveaway: null,
    ticketPromo: null,
    consessions: "$2 Consessions",
    otherActivities: null,
  },
  {
    id: 9,
    logo: kansas,
    date: "01-14-2024",
    time: "6:00 PM",
    theme: "Pink Game",
    sponsor: "OU Health",
    associatedSponsor: null,
    sspTickets: null,
    anthem: "Choir",
    emcee: "Tommy",
    pa: "Justin Wollard",
    colorGuard: null,
    halftime: "Bethel Lady Pirates Basketball Scrimmage",
    recognitions: "Patriot of the Game",
    kidsZone: null,
    concourse: null,
    spirit: null,
    giveaway: null,
    ticketPromo: null,
    consessions: "$2 Consessions",
    otherActivities: null,
  },
  {
    id: 10,
    logo: texas,
    date: "01-14-2024",
    time: "6:00 PM",
    theme: "Pink Game",
    sponsor: "OU Health",
    associatedSponsor: null,
    sspTickets: null,
    anthem: "Choir",
    emcee: "Tommy",
    pa: "Justin Wollard",
    colorGuard: null,
    halftime: "Bethel Lady Pirates Basketball Scrimmage",
    recognitions: "Patriot of the Game",
    kidsZone: null,
    concourse: null,
    spirit: null,
    giveaway: null,
    ticketPromo: null,
    consessions: "$2 Consessions",
    otherActivities: null,
  },
  {
    id: 11,
    logo: bama,
    date: "01-14-2024",
    time: "6:00 PM",
    theme: "Pink Game",
    sponsor: "OU Health",
    associatedSponsor: null,
    sspTickets: null,
    anthem: "Choir",
    emcee: "Tommy",
    pa: "Justin Wollard",
    colorGuard: null,
    halftime: "Bethel Lady Pirates Basketball Scrimmage",
    recognitions: "Patriot of the Game",
    kidsZone: null,
    concourse: null,
    spirit: null,
    giveaway: null,
    ticketPromo: null,
    consessions: "$2 Consessions",
    otherActivities: null,
  },
  {
    id: 12,
    logo: ducks,
    date: "01-14-2024",
    time: "6:00 PM",
    theme: "Pink Game",
    sponsor: "OU Health",
    associatedSponsor: null,
    sspTickets: null,
    anthem: "Choir",
    emcee: "Tommy",
    pa: "Justin Wollard",
    colorGuard: null,
    halftime: "Bethel Lady Pirates Basketball Scrimmage",
    recognitions: "Patriot of the Game",
    kidsZone: null,
    concourse: null,
    spirit: null,
    giveaway: null,
    ticketPromo: null,
    consessions: "$2 Consessions",
    otherActivities: null,
  },
  {
    id: 13,
    logo: huskies,
    date: "01-14-2024",
    time: "6:00 PM",
    theme: "Pink Game",
    sponsor: "OU Health",
    associatedSponsor: null,
    sspTickets: null,
    anthem: "Choir",
    emcee: "Tommy",
    pa: "Justin Wollard",
    colorGuard: null,
    halftime: "Bethel Lady Pirates Basketball Scrimmage",
    recognitions: "Patriot of the Game",
    kidsZone: null,
    concourse: null,
    spirit: null,
    giveaway: null,
    ticketPromo: null,
    consessions: "$2 Consessions",
    otherActivities: null,
  },
  {
    id: 14,
    logo: fsu,
    date: "01-14-2024",
    time: "6:00 PM",
    theme: "Pink Game",
    sponsor: "OU Health",
    associatedSponsor: null,
    sspTickets: null,
    anthem: "Choir",
    emcee: "Tommy",
    pa: "Justin Wollard",
    colorGuard: null,
    halftime: "Bethel Lady Pirates Basketball Scrimmage",
    recognitions: "Patriot of the Game",
    kidsZone: null,
    concourse: null,
    spirit: null,
    giveaway: null,
    ticketPromo: null,
    consessions: "$2 Consessions",
    otherActivities: null,
  },
  {
    id: 15,
    logo: texasAandM,
    date: "01-14-2024",
    time: "6:00 PM",
    theme: "Pink Game",
    sponsor: "OU Health",
    associatedSponsor: null,
    sspTickets: null,
    anthem: "Choir",
    emcee: "Tommy",
    pa: "Justin Wollard",
    colorGuard: null,
    halftime: "Bethel Lady Pirates Basketball Scrimmage",
    recognitions: "Patriot of the Game",
    kidsZone: null,
    concourse: null,
    spirit: null,
    giveaway: null,
    ticketPromo: null,
    consessions: "$2 Consessions",
    otherActivities: null,
  },
  {
    id: 16,
    logo: michigan,
    date: "01-14-2024",
    time: "6:00 PM",
    theme: "Pink Game",
    sponsor: "OU Health",
    associatedSponsor: null,
    sspTickets: null,
    anthem: "Choir",
    emcee: "Tommy",
    pa: "Justin Wollard",
    colorGuard: null,
    halftime: "Bethel Lady Pirates Basketball Scrimmage",
    recognitions: "Patriot of the Game",
    kidsZone: null,
    concourse: null,
    spirit: null,
    giveaway: null,
    ticketPromo: null,
    consessions: "$2 Consessions",
    otherActivities: null,
  },
];

export const mockRows = [
  {
    label: "",
    value: "logo",
  },
  {
    label: "Date",
    value: "date",
  },
  {
    label: "Time",
    value: "time",
  },
  {
    label: "Theme",
    value: "theme",
  },
  {
    label: "Sponsor",
    value: "sponsor",
  },
  {
    label: "Associated Sponsor",
    value: "associatedSponsor",
  },
  {
    label: "SSP Tickets",
    value: "sspTickets",
  },
  {
    label: "Anthem",
    value: "anthem",
  },
  {
    label: "Emcee",
    value: "emcee",
  },
  {
    label: "PA",
    value: "pa",
  },
  {
    label: "Color Guard",
    value: "colorGuard",
  },
  {
    label: "Halftime",
    value: "halftime",
  },
  {
    label: "Recognitions",
    value: "recognitions",
  },
  {
    label: "Kids Zone",
    value: "kidsZone",
  },
  {
    label: "Concourse",
    value: "concourse",
  },
  {
    label: "Spirit",
    value: "spirit",
  },
  {
    label: "Giveaway",
    value: "giveaway",
  },
  {
    label: "Ticket Promo",
    value: "ticketPromo",
  },
  {
    label: "Consessions",
    value: "consessions",
  },
  {
    label: "Other Activities",
    value: "otherActivities",
  },
];
